server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_REALM_URI:http://localhost:8080/realms/ticketera}
  cloud:
    gateway:
      routes:
        - id: public-ticketera-api
          uri: ${EVENTS_API_URI:http://localhost:8082}
          predicates:
            - Path=/api/public/ticketera/**
          filters:
            - StripPrefix=2

        - id: private-ticketera-api
          uri: ${EVENTS_API_URI:http://localhost:8082}
          predicates:
            - Path=/api/private/ticketera/**
          filters:
            - StripPrefix=2


events-gateway:
  allowed-origins:
    - ${ALLOWED_ORIGIN_1:http://localhost:5173}
    - ${ALLOWED_ORIGIN_2:http://localhost:5173}
    - ${ALLOWED_ORIGIN_3:http://localhost:5173}
    - ${ALLOWED_ORIGIN_4:http://localhost:5173}
    - ${ALLOWED_ORIGIN_5:http://localhost:5173}
    - ${ALLOWED_ORIGIN_6:http://localhost:5173}

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    org.springframework.security: DEBUG
#
