server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_REALM_URI:http://localhost:8080/realms/ticketera}
  cloud:
    gateway:
      routes:
        - id: keycloak-auth
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: public-ticketera-api
          uri: http://localhost:8082
          predicates:
            - Path=/api/public/ticketera/**
          filters:
            - StripPrefix=2

        - id: private-ticketera-api
          uri: http://localhost:8082
          predicates:
            - Path=/api/private/ticketera/**
          filters:
            - StripPrefix=2


events-gateway:
    allowed-origins:
      - http://localhost:5173

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    org.springframework.security: DEBUG
#
