server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_REALM_URI:http://localhost:8080/realms/ticketera}
  cloud:
    gateway:
      routes:
        - id: events-api
          uri: ${EVENTS_API_URI:http://localhost:8082}
          predicates:
            - Path=/ticketera/**

events-gateway:
    allowed-origins:
      - http://localhost:5173

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    org.springframework.security: DEBUG
#
