apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-gateway
  namespace: event-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-gateway
  template:
    metadata:
      labels:
        app: event-gateway
    spec:
      containers:
        - name: event-gateway
          image: ghcr.io/leandrodalbo/event-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              hostPort: 80
          env:
            - name: KEYCLOAK_REALM_URI
              value: http://keycloak.event-auth.svc.cluster.local:8080/realms/ticketera
            - name: EVENTS_API_URI
              value: http://api:8082
