apiVersion: v1
kind: Service
metadata:
  name: event-gateway
  namespace: event-gateway
spec:
  selector:
    app: event-gateway
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8081
      nodePort: 30081
